"""Regulatory disclaimers for MedGemma MCP output.

Required by Google's Health AI Developer Foundations terms of use
and FDA guidance on AI/ML-based Software as a Medical Device (SaMD).
"""

MEDICAL_DISCLAIMER = (
    "IMPORTANT: This analysis is generated by an AI system (MedGemma) and is "
    "intended for research and development purposes only. It is NOT a substitute "
    "for professional medical advice, diagnosis, or treatment. All outputs require "
    "independent verification and clinical correlation by qualified healthcare "
    "professionals before any patient care applications. MedGemma is not FDA-cleared "
    "for clinical diagnosis."
)

DEVELOPER_DISCLAIMER = (
    "This tool is provided as infrastructure for healthcare AI developers. "
    "Developers are responsible for appropriate validation, adaptation, and "
    "meaningful modification before any downstream clinical application."
)
